#if HAS_SPAN
using System.Buffers;
#endif
#if NETCOREAPP2_1_OR_GREATER
using System.Buffers.Binary;
#endif
using System.Diagnostics;

using static QRCoder.QRCodeGenerator;

namespace QRCoder;


/// <summary>
/// Represents a QR code generator that outputs QR codes as bitmap byte arrays.
/// </summary>
// ReSharper disable once InconsistentNaming
public class BitmapByteQRCode : AbstractQRCode, IDisposable
{
    // First 32 bytes of a bitmap file header (for 24-bit bitmaps)
#if HAS_SPAN
    private static ReadOnlySpan<byte> _bitmapHeader =>
#else
    private static readonly byte[] _bitmapHeader =
#endif
    [
        0x42, 0x4D, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x36, 0x00, 0x00, 0x00, 0x28, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x18, 0x00, 0x00, 0x00
    ];

    /// <summary>
    /// Initializes a new instance of the <see cref="BitmapByteQRCode"/> class.
    /// Constructor without parameters to be used in COM objects connections.
    /// </summary>
    public BitmapByteQRCode() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="BitmapByteQRCode"/> class with the specified <see cref="QRCodeData"/>.
    /// </summary>
    /// <param name="data"><see cref="QRCodeData"/> generated by the QRCodeGenerator.</param>
    public BitmapByteQRCode(QRCodeData data) : base(data) { }

    /// <summary>
    /// Returns the QR code graphic as a bitmap byte array.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <returns>Returns the QR code graphic as a bitmap byte array.</returns>
    public byte[] GetGraphic(int pixelsPerModule)
        => GetGraphic(pixelsPerModule, [0x00, 0x00, 0x00], [0xFF, 0xFF, 0xFF]);

    /// <summary>
    /// Returns the QR code graphic as a bitmap byte array.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColorHtmlHex">The color of the dark modules in HTML hex format.</param>
    /// <param name="lightColorHtmlHex">The color of the light modules in HTML hex format.</param>
    /// <returns>Returns the QR code graphic as a bitmap byte array.</returns>
    public byte[] GetGraphic(int pixelsPerModule, string darkColorHtmlHex, string lightColorHtmlHex)
        => GetGraphic(pixelsPerModule, darkColorHtmlHex.HexColorToByteArray(), lightColorHtmlHex.HexColorToByteArray());

    /// <summary>
    /// Returns the QR code graphic as a bitmap byte array.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColorRgb">The color of the dark modules as an RGB byte array.</param>
    /// <param name="lightColorRgb">The color of the light modules as an RGB byte array.</param>
    /// <returns>Returns the QR code graphic as a bitmap byte array.</returns>
    public byte[] GetGraphic(int pixelsPerModule, byte[] darkColorRgb, byte[] lightColorRgb)
    {
        // Pre-calculate color/module bytes
        int bytesPerModule = pixelsPerModule * 3;
        byte[] moduleDark = new byte[bytesPerModule];
        byte[] moduleLight = new byte[bytesPerModule];

        for (int i = 0; i < bytesPerModule; i += 3)
        {
            moduleDark[i] = darkColorRgb[2];
            moduleDark[i + 1] = darkColorRgb[1];
            moduleDark[i + 2] = darkColorRgb[0];
            moduleLight[i] = lightColorRgb[2];
            moduleLight[i + 1] = lightColorRgb[1];
            moduleLight[i + 2] = lightColorRgb[0];
        }

        var moduleMatrix = QrCodeData.ModuleMatrix;
        var sideLength = moduleMatrix.Count * pixelsPerModule;

        // The size of each row must be rounded up to a multiple of 4 bytes by padding.
        // Pre-calculate padding bytes
        int rowByteLength = sideLength * 3;
        int paddingLen = -rowByteLength & 3;
        Debug.Assert(paddingLen >= 0 && paddingLen < 4 && (rowByteLength + paddingLen) % 4 == 0);

        // Calculate filesize (header + pixel data + padding)
        int fileSize = 54 + (rowByteLength + paddingLen) * sideLength;

        // Bitmap container
        byte[] bmp = new byte[fileSize];

        // Header
#if HAS_SPAN
        _bitmapHeader.CopyTo(bmp);
#else
        Array.Copy(_bitmapHeader, 0, bmp, 0, _bitmapHeader.Length);
#endif

        // File size
        CopyIntAs4ByteToArray(fileSize, 2, bmp);
        // Width
        CopyIntAs4ByteToArray(sideLength, 18, bmp);
        // Height
        CopyIntAs4ByteToArray(sideLength, 22, bmp);

        // Header is 54 bytes in total, remaining bytes are zero.
        Debug.Assert(bmp[10] == 54);
        int ix = 54;

        // Draw qr code
        for (int y = moduleMatrix.Count - 1; y >= 0; y--)
        {
            var modules = moduleMatrix[y];

            // Write data for first line of pixelsPerModule lines
            int lineStart = ix;
            for (int x = 0; x < modules.Length; x++)
            {
                byte[] module = modules[x] ? moduleDark : moduleLight;
                Array.Copy(module, 0, bmp, ix, module.Length);
                ix += module.Length;
            }
            // Add padding (to make line length a multiple of 4)
            ix += paddingLen;
            int lineLength = ix - lineStart;

            // Re-write (copy) first line (pixelsPerModule - 1) times
            for (int pm = pixelsPerModule - 1; pm > 0; pm--)
            {
                // Draw pixels
                Array.Copy(bmp, lineStart, bmp, ix, lineLength);
                ix += lineLength;
            }
        }

        return bmp;
    }


    /// <summary>
    /// Converts an integer to a 4 bytes and writes them to a byte array at given position
    /// </summary>
    /// <param name="inp">The integer to convert.</param>
    /// <param name="destinationIndex">Index of destinationArray where the converted bytes are written to</param>
    /// <param name="destinationArray">Destination byte array that receives the bytes</param>
    private static void CopyIntAs4ByteToArray(int inp, int destinationIndex, byte[] destinationArray)
    {
#if NETCOREAPP2_1_OR_GREATER
        BinaryPrimitives.WriteInt32LittleEndian(destinationArray.AsSpan(destinationIndex), inp);
#else
        unchecked
        {
            destinationArray[destinationIndex + 3] = (byte)(inp >> 24);
            destinationArray[destinationIndex + 2] = (byte)(inp >> 16);
            destinationArray[destinationIndex + 1] = (byte)(inp >> 8);
            destinationArray[destinationIndex + 0] = (byte)(inp);
        }
#endif
    }
}


/// <summary>
/// Provides helper functions for creating bitmap byte array QR codes.
/// </summary>
public static class BitmapByteQRCodeHelper
{
    /// <summary>
    /// Creates a bitmap byte array QR code with a single function call.
    /// </summary>
    /// <param name="plainText">The text or payload to be encoded inside the QR code.</param>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColorHtmlHex">The color of the dark modules in HTML hex format.</param>
    /// <param name="lightColorHtmlHex">The color of the light modules in HTML hex format.</param>
    /// <param name="eccLevel">The level of error correction data.</param>
    /// <param name="forceUtf8">Specifies whether the generator should be forced to work in UTF-8 mode.</param>
    /// <param name="utf8BOM">Specifies whether the byte-order-mark should be used.</param>
    /// <param name="eciMode">Specifies which ECI mode should be used.</param>
    /// <param name="requestedVersion">Sets the fixed QR code target version.</param>
    /// <returns>Returns the QR code graphic as a bitmap byte array.</returns>
    public static byte[] GetQRCode(string plainText, int pixelsPerModule, string darkColorHtmlHex,
        string lightColorHtmlHex, ECCLevel eccLevel, bool forceUtf8 = false, bool utf8BOM = false,
        EciMode eciMode = EciMode.Default, int requestedVersion = -1)
    {
        using var qrGenerator = new QRCodeGenerator();
        using var qrCodeData = qrGenerator.CreateQrCode(plainText, eccLevel, forceUtf8, utf8BOM, eciMode,
                requestedVersion);
        using var qrCode = new BitmapByteQRCode(qrCodeData);
        return qrCode.GetGraphic(pixelsPerModule, darkColorHtmlHex, lightColorHtmlHex);
    }

    /// <summary>
    /// Creates a bitmap byte array QR code with a single function call.
    /// </summary>
    /// <param name="txt">The text or payload to be encoded inside the QR code.</param>
    /// <param name="eccLevel">The level of error correction data.</param>
    /// <param name="size">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <returns>Returns the QR code graphic as a bitmap byte array.</returns>
    public static byte[] GetQRCode(string txt, QRCodeGenerator.ECCLevel eccLevel, int size)
    {
        using var qrGen = new QRCodeGenerator();
        using var qrCode = qrGen.CreateQrCode(txt, eccLevel);
        using var qrBmp = new BitmapByteQRCode(qrCode);
        return qrBmp.GetGraphic(size);

    }
}
