name: Format (Pull Request)
on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      EnableWindowsTargeting: true
    steps:
    - uses: actions/checkout@v4
      name: Checkout Code

    - name: Install additional .NET SDKs
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Format solution
      run: dotnet format --verify-no-changes --severity error
